/**
 * copy-traces.mjs
 *
 * Copies the raw trace JSON files generated by `forge test --match-contract TraceExporter`
 * from ./traces/ into viz/fixtures/ with the correct .fixture.json naming.
 *
 * Usage:
 *   node viz/scripts/copy-traces.mjs
 *
 * Or via the combined regen command (see docs/notes.md):
 *   forge test --match-contract TraceExporter && node viz/scripts/copy-traces.mjs
 */
import { copyFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(scriptDir, '..', '..');
const tracesDir = join(repoRoot, 'traces');
const fixturesDir = join(scriptDir, '..', 'fixtures');

const COPIES = [
  { src: 'trace-small-swap.json', dst: 'trace-small-swap.fixture.json' },
  { src: 'trace-large-swap.json', dst: 'trace-large-swap.fixture.json' },
];

let ok = true;
for (const { src, dst } of COPIES) {
  const srcPath = join(tracesDir, src);
  const dstPath = join(fixturesDir, dst);
  if (!existsSync(srcPath)) {
    console.error(`MISSING ${srcPath} — run: forge test --match-contract TraceExporter`);
    ok = false;
    continue;
  }
  copyFileSync(srcPath, dstPath);
  console.log(`copied  ${src} → fixtures/${dst}`);
}

process.exit(ok ? 0 : 1);
